version: '3'

services:

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.7.6-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth:
    image: quay.io/openware/authz-dummy:0.1.1
    ports:
      - "8005:8005"
    environment:
      DUMMY_USER_EMAIL: "admin@barong.io"
      DUMMY_USER_UID: "U123456789"
      DUMMY_USER_ROLE: "superadmin"
      DUMMY_USER_LEVEL: 3
      DUMMY_USER_STATE: "active"
      DUMMY_JWT_PRIVKEY_FILE: "/secrets/rsa-key"
      DUMMY_JWT_TTL: 86400
    volumes:
      - ./secrets:/secrets:ro

  gateway:
    image: quay.io/datawire/ambassador:0.50.0-rc3
    ports:
      - "8080:80"
    depends_on:
      - auth
    volumes:
      - ./gateway:/ambassador/ambassador-config/:ro
    entrypoint:
      - sh
      - -exc
      - |
        # Allow accessing host's 0.0.0.0 so we can connect to a local peatio
        # from the gateway container
        ip -4 route list match 0/0 | awk '{print $$3" peatio.local"}' >> /etc/hosts
        ip -4 route list match 0/0 | awk '{print $$3" ws.local"}' >> /etc/hosts
        # Continue with the default entrypoint
        ./entrypoint.sh

  vault:
    image: vault:1.0.1
    ports:
      - "8200:8200"
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
